import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { requireEnv } from '@/lib/env';
import { verifyResendSignature } from '@/lib/resendWebhook';
import { captureError } from '@/lib/observability';

/**
 * Resend webhook receiver.
 *
 * Configure in Resend dashboard:
 *   Endpoint: https://<app>/api/resend/webhook
 *   Events:   email.bounced, email.complained
 *   Secret:   Generated by Resend, store as RESEND_WEBHOOK_SECRET
 *
 * On bounce/complaint, we set the recipient user's `marketingOptOut=true`
 * so the drip campaign service excludes them on the next run. Transactional
 * emails (welcome, password reset, etc.) are NOT affected — those are gated
 * by business need, not marketing preference.
 */
export async function POST(request: NextRequest) {
  const body = await request.text();
  const secret = requireEnv('RESEND_WEBHOOK_SECRET');

  const valid = verifyResendSignature({
    body,
    svixId: request.headers.get('svix-id'),
    svixTimestamp: request.headers.get('svix-timestamp'),
    svixSignature: request.headers.get('svix-signature'),
    secret,
  });

  if (!valid) {
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 });
  }

  try {
    const event = JSON.parse(body) as {
      type?: string;
      data?: { email_id?: string; to?: string[]; bounce?: { type?: string } };
    };

    const toList = event.data?.to ?? [];
    const primaryEmail = toList[0];
    if (!primaryEmail) {
      return NextResponse.json({ received: true });
    }

    switch (event.type) {
      case 'email.bounced': {
        // Only opt out on hard bounces. Soft bounces (e.g. full mailbox)
        // will recover; opting out on them loses deliverability unnecessarily.
        const bounceType = event.data?.bounce?.type ?? '';
        if (bounceType !== 'hard_bounce' && bounceType !== 'hard') {
          return NextResponse.json({ received: true, skipped: 'soft bounce' });
        }
        await prisma.user.updateMany({
          where: { email: primaryEmail },
          data: { marketingOptOut: true },
        });
        break;
      }

      case 'email.complained': {
        // Spam complaint — always opt out.
        await prisma.user.updateMany({
          where: { email: primaryEmail },
          data: { marketingOptOut: true },
        });
        break;
      }
      // Other events (delivered, opened, clicked) are ignored.
    }

    return NextResponse.json({ received: true });
  } catch (error) {
    captureError(error, { tag: 'resend:webhook' });
    // Return 500 so Resend retries for transient DB failures.
    return NextResponse.json({ error: 'Handler failed' }, { status: 500 });
  }
}
